name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GENERAL_TOKEN }}
        issue-message: "Wow, you just created your first issue on this project, that's so cool. Make sure to wait till you are allowed to work on this before you do and when you are allowed to, don't forget to mention this issue in your pull request[Automated]"
        pr-message: "Congratualations on creating your first pull request on this project🥂🥳 I hope you continue to make this project better[Automated]"
    - uses: kyoncy/issue-comment-actions@v1
      with:
        repo-token: ${{ secrets.GENERAL_TOKEN }}
        message: "Thanks for creating this issue, make sure to wait till you are allowed to work on this before you do and when you are allowed to, don't forget to mention this issue in your pull request[Automated]"
    - uses: github-actions-up-and-running/pr-comment@v1.0.1
      with:
        repo-token: ${{ secrets.GENERAL_TOKEN }}
        message: "Thanks for proposing to make changes to this project, your code will be reviewed soon"


        
