labels:
  - name: invalid
    labeled:
      issue:
        body: Please follow the issue templates.
        action: close
      pr:
        body: Thank you @{{ pull_request.user.login }} for suggesting this. Please follow the pull request templates.
        action: close
  - name: wontfix
    labeled:
      issue:
        body: This will not be worked on but we appreciate your contribution.
        action: close
    unlabeled:
      issue:
        body: This has become active again.
        action: open
  - name: duplicate
    labeled:
      issue:
        body: This issue already exists.
        action: close
  - name: '🚦 status: awaiting approval'
    labeled:
      issue:
        body: |
         This issue is waiting to be approved so it's locked until approved      
         Thank you @{{ issue.user.login }} for creating an issue, while you wait for a response, consider reading the <a href="https://github.com/Dun-sin/Code-Magic/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face
        locking: lock
  - name: '🏁 status: ready for dev'
    labeled:
      issue:
        body: |
         This issue is ready for dev and assigned to anyone who proper asks
        locking: unlock
